###############################################
###############################################
## Questo makefile controlla la generazione  ##
## della documentazione per il progatto Fat  ##
###############################################
###############################################

.PHONY: all

all:
	-rm -fr html
	doxygen 